### ISSUE TITLE
Consider renaming the workbench?

### ISSUE THREAD

**Issue by luzpaz** [mnesarco/MarzWorkbench#1]
It just has better recognition of what it does. We have workbenches like [Flamingo](https://wiki.freecadweb.org/Flamingo_Workbench) and Dodo (which is the Python3/Qt5 port of flamingo) and there is a sentiment that the name of these workbenches don't lend themselves to the workbenches being utilized. So it's something you may want to consider... ?

**Comment by mnesarco** [comment]
Something like Marz Guitar Designer?

**Comment by luzpaz** [comment]
Seems to work. Lets ask yorik to weigh in.  
CC @yorikvanhavre

**Comment by yorikvanhavre** [comment]
Ultimately I think the decision is that author's. Both are fine. Having a more "technical" name such as "guitar and bass designer tool" is of course easier on the user at first read, but "Marz" makes it nicer to "package" into a nice "branding" or "product". Depends much on what your idea is for the future I would say, if you are just releasing a utility or if you are growing it into something to advertise around with pride ;)

In any case the best thing to do IMHO is to have a nice README (which you have!! Impressive!) that starts with a description of the WB, so it appears nicely in the FreeCAD addon manager and user don't loose hours trying to figure out what it does.

**Comment by mnesarco** [comment]
@luzpaz @yorikvanhavre 

I have updated the UI and README to reflect the new Name.

![ui](https://github.com/mnesarco/MarzWorkbench/raw/master/docs/images/ui-elements.png)

**Comment by luzpaz** [comment]
I also mean renaming the github repo, not just the workbench name.

**Comment by mnesarco** [comment]
Hi @luzpaz , I don't think it is a good idea to rename the Github Repo after I have shared links to it, people will be lost.
