### ISSUE TITLE
Zero Fret

### ISSUE THREAD

**Issue by kenf1a** [mnesarco/MarzWorkbench#10]
Thanks for making this workbench!  I read that a zero fret neck is supported but I've not been able to find the right parameter or command anywhere within the workbench.  Can you please explain or point me to how this is done?

**Comment by mnesarco** [comment]
Simply set the Nut offset to something greater than zero:

![screenshot_14](https://user-images.githubusercontent.com/1087317/134392483-452e2ea6-3cb8-4526-918c-4e4c86c3d45e.png)

**Comment by kenf1a** [comment]
Thanks for the quick reply!  Not sure how I missed that.

One other thing, I'm having trouble getting the nut width correct.  My target is a 42mm nut.  With 36mm string spacing and 3mm margin on each side I should get 42 right?  But now with equal center string spacing I set the distance to 32.5mm and I get a 42mm nut.  Is there something I'm missing?

**Comment by mnesarco** [comment]
Maybe you are missing string gauge. You can change string gauges and check again. Also this is measured at zero fret position. So if you are using nut offset greater than zero, the real neck width at nut will be different because the fretboard is not a rectangle.

**Comment by mnesarco** [comment]
I did a quick check and apparently side margin is applied twice. I will do a review....

**Comment by mnesarco** [comment]
The Side Margin calculation is fixed now. So please upgrade using the Addon Manager or Extman.

**Comment by kenf1a** [comment]
Great, thanks for the fast response!  I'm looking forward to your new developments.

**Comment by mnesarco** [comment]
![screenshot_15](https://user-images.githubusercontent.com/1087317/134419519-6910226f-4de2-4f24-b678-b0895c349e04.png)

**Comment by mnesarco** [comment]
Take into account that the new version is coming so I will soon stop backporting fixes to this version.

https://www.youtube.com/watch?v=qEHmJ4XjxN8
