### ISSUE TITLE
headstock text in svg file

### ISSUE THREAD

**Issue by Cysign** [mnesarco/MarzWorkbench#14]
I'm testing the example_custom_headstock.svg right now. I'd like to replace the text 'Test' with another text. But I couldn't figure out how to set it up, so Freecad can read it properly. Is there a documentation about this?
Do I have to use a font and transform it into a vector?

And how would I decide if it's a hole or a pocket? Are those things color coded?

**Comment by mnesarco** [comment]
Yes the documentation is in the wiki: https://github.com/mnesarco/MarzWorkbench/wiki/Custom-Shapes

Any shape (including text) must be convertetd to path before importing to freecad.

**Comment by Cysign** [comment]
Nice Wiki. But I'm still not surehow to use it.
Can I name the IDs using Inkscape or do I have to modify the file using an text editor?

**Comment by Cysign** [comment]
https://www.file-upload.net/download-14788003/screenshot_IDs.png.html

I can see some IDs that look familiar... but all those #pathXXX files?

**Comment by mnesarco** [comment]
You can set the id of objects directly in inkscape. I am from my phone now so no snapshot to show you how. But a quick google search can help.

**Comment by mnesarco** [comment]
Inkscape / menu / Object / Object Properties

![screenshot_46](https://user-images.githubusercontent.com/1087317/146861689-70a09260-cd5b-4e48-adc6-b94aec11b923.png)

**Comment by Cysign** [comment]
Can I use IDs multiple times or does every shape have to use it'S own ID?

I created a text using the text tool in Inkscape.
Then I transformed this text to path.
Now I gave every object it's own ID, but the result doesn't look what I wanted it to look like:
https://www.file-upload.net/download-14788027/screenshot_headstock.png.html

**Comment by mnesarco** [comment]
Once you transformed text to path, there will be many paths, but you can merge all of them into one big path and then assign the id.

There are many Inkscape tutorials: https://inkscape.org/learn/tutorials/ once you know the basic operations it will be very straightforward.

**Comment by Cysign** [comment]
I merged the whole path into a single opject. But a single part of it still won't be displayed properly.
Here's my testfile: https://www.file-upload.net/download-14789618/example_custom_headstock.svg.html

I labeled it "lesson 01" - but the 1 won't display proberly.

**Comment by mnesarco** [comment]
FreeCAD's svg importer is quite basic. If the paths are not connected, you must set an id to each part.
[example_custom_headstock_fixed.svg.zip](https://github.com/mnesarco/MarzWorkbench/files/7759447/example_custom_headstock_fixed.svg.zip)
![screenshot_47](https://user-images.githubusercontent.com/1087317/147023355-237f3185-3a42-41d6-be65-69af4b20e19c.png)

**Comment by mnesarco** [comment]
The C++ version (WIP) does not use FreeCAD's svg importer. I wrote an svg importer from scratch highly tuned for this usage. I was trying to release it before xmas, but it was impossible due to time constraints.
