### ISSUE TITLE
I have a question please (Imgui)

### ISSUE THREAD

**Issue by MariwanJ** [mnesarco/MarzWorkbench#21]
HI, 
You mentioned at the forum that you have used Imgui toolkit .. but I cannot see in your code the library. 
Would you please provide me some info?
I need to know if one can draw things inside FreeCAD using Imgui .. not in Imgui windows. 

Thanks in advance 
Mariwna

**Comment by mnesarco** [comment]
Hi @MariwanJ 
I have not used ImGui in MarzWorkbench, I have used ImGui in a different project that is the successor of MarzWorkbench but it is not public yet.

**Comment by MariwanJ** [comment]
ok thanks
