### ISSUE TITLE
Questions...

### ISSUE THREAD

**Issue by ewidance** [mnesarco/MarzWorkbench#22]
Hi,

First of all, thank you for the huge job. 
Since I'm an aboslute beginner in guitar build, I got some questions :
- There are bridge vars in the instrument parameters section. However,i dont see the bridge or effect on var modification. Is this part in progress? 
- Since frets are not displayed, why is there settings for frets caracteristics? Dos this impact fret position calculation? 
- In example svg  files provided, it seems bridge mic is incorredctly positionned. It conflicts with bridge position. Have you seen it or is it a mis-understanding of mine?
- Is it possible to use this plugin to build a guitar without plate attached to the top? (ie : strat or tele) How? Would it be possible to provide an example file? 
- Would it be possible to improve documentation for explainng var per var the setup and effect on the model? May I help?

Thanks a lot for the answers!

**Comment by mnesarco** [comment]
> * There are bridge vars in the instrument parameters section. However,i dont see the bridge or effect on var modification. Is this part in progress?

**String Distance Projection** is used to calculate the Scale/Fretboard/Neck geometry. Other parameters like height, and compensation are there for future align of imported Bridge parts.

> * Since frets are not displayed, why is there settings for frets caracteristics? Dos this impact fret position calculation?

Some have impact on the slot geometry like tang depth and width. Crown geometry parameters are there for future generation of frets.

> * In example svg  files provided, it seems bridge mic is incorredctly positionned. It conflicts with bridge position. Have you seen it or is it a mis-understanding of mine?

I don't understand what do you mean here. Examples are there only to demo how to name your own path objects so they can be imported and carved from body/headstock/fretboard. The correct positioning of that geometry is a task for the designer of the guitar, they are imported as they are.

> * Is it possible to use this plugin to build a guitar without plate attached to the top? (ie : strat or tele) How? Would it be possible to provide an example file?

Just set **Body/Top Thickness** to zero (0).

> * Would it be possible to improve documentation for explainng var per var the setup and effect on the model? May I help?
> 

It would be a great contribution 👍🏼 

In the mean time: https://github.com/mnesarco/MarzWorkbench/wiki
