### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by tresmolo** [mnesarco/MarzWorkbench#25]
Hello Frank,
Thank you for your work and your talent. Some questions :
When I adjust the length of the pocket in the body, for example 77 mm for a stratocaster, when creating the neck, the length of the assembly is not modified according to this dimension, and the neck is therefore badly positioned, in this case shifted to the bridge.
.
Moreover, when I create an element (body, neck, etc.), and delete it, it is not possible to recreate it...

Last problem, in case of modification of a neck parameter or other, the auto-update does not work and FreeCad is blocked. (I use version 0.21)
Thanks in advance. (And sorry for Google translate 😉)
Pascal

**Comment by mnesarco** [comment]
Hello Pascal,

> When I adjust the length of the pocket in the body, for example 77 mm for a stratocaster, when creating the neck, the length of the assembly is not modified according to this dimension, and the neck is therefore badly positioned, in this case shifted to the bridge. . 

Length of the pocked is used only to position the neck into the body (how much the neck goes into the body). if you want to modify the length of the heel you need to play with transition start and join fret.

> Moreover, when I create an element (body, neck, etc.), and delete it, it is not possible to recreate it...
 
Yes this a known problem. Please do not delete the generated objects, just modify the parameters. 

> Last problem, in case of modification of a neck parameter or other, the auto-update does not work and FreeCad is blocked. (I use version 0.21)

Maybe auto-update is not compatible with latest changes in FC, I have not checked.

**Comment by mnesarco** [comment]
Fixed on 1.0.1 preview
