### ISSUE TITLE
Inlay import

### ISSUE THREAD

**Issue by zu4lu** [mnesarco/MarzWorkbench#27]
Hi, i made an svg from a jpg in inkscape, created with trace bitmap a path, named it F12_ , but get the error
"The SVG File does not contain any inlay path". The imported files are split into pieces, though i combined it in inkscape.
Michael

**Comment by mnesarco** [comment]
`F12_` is not valid, it must be `f12_` (in lower case as showed in the wiki). Anyway, if you post your svg file maybe i can help more.

**Comment by zu4lu** [comment]
thanks,

Am Mittwoch, November 15, 2023 14:05 CET, schrieb Frank David Martínez M ***@***.***>:
 
 
F12_ is not valid, it must be f12_ (in lower case as showed in the wiki). Anyway, if you post your svg file maybe i can help more.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "https://github.com/mnesarco/MarzWorkbench/issues/27#issuecomment-1812505927", "url": "https://github.com/mnesarco/MarzWorkbench/issues/27#issuecomment-1812505927", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]***>
-- 
lg
Michael Kaufmann

**Comment by zu4lu** [comment]
i found it, the inlay must not be filled, only strokes are allowed.
