### ISSUE TITLE
Neck Pocket Into Slicing Software

### ISSUE THREAD

**Issue by Arayl96** [mnesarco/MarzWorkbench#38]
Hey i tried to put a body and template into a slicing/CAM software and the top and bottom layers are separating, the only change i made to the file from the previous body in the screenshots before was disable the neck pocket, when it was previously enabled. And since it is still considered the same file i cant edit it in the CAM software. 

![LVB1sGeR70](https://github.com/mnesarco/MarzWorkbench/assets/161767535/da190fc6-951f-4e80-82bb-03eb95622b88)

![firefox_iOtTLfEE4I](https://github.com/mnesarco/MarzWorkbench/assets/161767535/a8945942-2c4b-445e-9477-2992a3e97c26)

![FreeCAD_W5JZD4dIbz](https://github.com/mnesarco/MarzWorkbench/assets/161767535/dcb4f3d2-31d0-464a-892f-d80b4ce04646)

![firefox_gjUZRK5MNY](https://github.com/mnesarco/MarzWorkbench/assets/161767535/72d1eb2b-424e-4d2a-b866-3d969fd14911)

**Comment by mnesarco** [comment]
Body Top and Body Back are separated pieces. What is the problem?
Do you want a single piece body? in that case set top body thickness to zero.

**Comment by Arayl96** [comment]
I know they are separate pieces but I don't want them separated I want them together like in the first two screenshots. If I set the top thickness to zero than I wont get the holes for the pots and the cavity will be open. like in the third screenshot. They aren't separated in a CAM software when a neck pocket is generated but they are separated in the software when a neck pocket isn't generated. And i'm unable to edit the CAM software to close the gap of the separation.

![FreeCAD_W5JZD4dIbz](https://github.com/mnesarco/MarzWorkbench/assets/161767535/34ae867a-6c13-441b-88bc-1e599d8b2e73)

![firefox_4XMasiyQX5](https://github.com/mnesarco/MarzWorkbench/assets/161767535/55a55850-03ab-4738-a812-8c30eb320aec)

 ![KeF0PiKVDw](https://github.com/mnesarco/MarzWorkbench/assets/161767535/9b8cec73-5c19-4831-beae-640221588e68)

**Comment by mnesarco** [comment]
The Marz Workbench generate two Parts , one for the Top and one for the Back in this scenario. Even that you see all the parts "assembled" in FreeCAD it does not mean they are prepared for a specific CAM workflow.  How you position or manage them in your **external software** (slicer/CAM) is out of scope. From the CAD perspective, Top and Back Parts are separated solids, you can fuse them if it is what you want, but there is a high probability that you get an object impossible to produce in a CNC router. Take into account that CNC routing is a subtractive process while 3D printing is an additive process. I don't mean that you cannot do that, but just be sure that you understand the process. CAM is not trivial and unfortunately i cannot help you with your external software, but maybe _inventables/easel_ forums can help.

**Comment by mnesarco** [comment]
@Arayl96 I understand your frustration, but as i said, I can't help you with the external software. On the CAD side, the Parts are correctly generated, placed and exported as individual parts. I barely have time to support this project and i see no bug here. Just fuse the two Parts before export as what you want is to machine both at once.

**Comment by mnesarco** [comment]
I would be great if some user with inventables/easel experience contribute some comments here to help Arayl96.

**Comment by mnesarco** [comment]
Hello @Arayl96 I am closing this issue as "out of scope". I'm sorry I couldn't help you this time.
