### ISSUE TITLE
Import Not Working Using Examples

### ISSUE THREAD

**Issue by andybrownri** [mnesarco/MarzWorkbench#4]
Hi There,

Thank you for putting these tools together, they're great.

In my first attempt to import any of the three example SVGs, nothing happens. What can I send you to take a look? 

Thank you,
Andy Brown

**Comment by mnesarco** [comment]
@andybrownri Maybe a short video of what are you doing.

**Comment by andybrownri** [comment]
Here you go... I'm basically trying to import a body, headstock and inlays and nothing happens. I'm using your files.

https://www.dropbox.com/s/0ac5nz7fqjtojsr/2020-08-28_10-24-16.mp4?dl=0

**Comment by mnesarco** [comment]
FreeCAD 0.18 is not supported. You need 0.19.
