### ISSUE TITLE
Guitar Workbench issue "No module named 'numpy.typing'

### ISSUE THREAD

**Issue by GuitarPile** [mnesarco/MarzWorkbench#42]
Hi,

I found an issue with Marz Workbench today 7th Nov. 2024: When starting Guitar Workbench a message "No module named 'numpy.typing' " appears and Guitar Workbench does not start.
- Any idea, why module is missing and is there a workaround? Marz Workbench was loaded/installed using Addon Manager in FreeCAD.

Rgds,
-pasi-

FreeCAD info:
[code]
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: releases/FreeCAD-0-21
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: Finnish/Finland (fi_FI)
Installed mods:   * Marz 0.1.10 [/code]

**Comment by mnesarco** [comment]
Thank you for reporting it. Maybe numpy.typing is not available in all version of FreeCAD. I removed the reference to avoid the issue. Pleas update to the latest version 0.1.11

**Comment by mnesarco** [comment]
Hello @GuitarPile can you confirm if this issue is fixed in 0.1.11 ?

**Comment by GuitarPile** [comment]
Hi,

I just re-installed Guitar Workbench and it works fine with FreeCAD ver.
0.21.2. I will download FreeCAD ver. 1.0 later and run quick test wit
Guitar.

Thank you!

pe 8. marrask. 2024 klo 14.00 Frank David Martínez M <
***@***.***> kirjoitti:

**Comment by mnesarco** [comment]
Excelent. Thank you.
