### ISSUE TITLE
3d model not generating when using an imported headstock

### ISSUE THREAD

**Issue by chugga-jpeg** [mnesarco/MarzWorkbench#46]
I have no idea what's going on. Everything else generates fine, but when I import the headstock, nothing generates, and the 3D fretboard flashes for a split second—that's all that happens.

**Comment by mnesarco** [comment]
Your svg file my have various possible errors. Look at this: https://www.youtube.com/watch?v=FoYInmWrkq4

**Comment by mnesarco** [comment]
@chugga-jpeg do you still need help with this?

**Comment by chugga-jpeg** [comment]
Hi,
Sorry for not responding. I have managed to solve the problem by
uninstalling and reinstalling the workbench

**Comment by mnesarco** [comment]
Ok, thank you for reporting
