### ISSUE TITLE
Custom shapes not working on Mac

### ISSUE THREAD

**Issue by OldManTies** [mnesarco/MarzWorkbench#5]
I've tried making my own SVG's for the body, which included a midline and contour (named respectively). This however did not work, I then tried using the example SVG's provided on this Wiki but sadly this wouldn't change the body shape either. 

Im running: 
- Mac OS high Sierra v10.13.6
- FreeCAD 0.18 (rev# 16146

Hopefully this issue can be resolved, I'd love to start using your software!

**Comment by mnesarco** [comment]
Hello @OldManTies, FreeCAD 0.18 is not supported by this extension. You need to try with FreeCAD 0.19_pre+
