### ISSUE TITLE
How does Midline length affect the position of the neck and body

### ISSUE THREAD

**Issue by IBuildGuitars** [mnesarco/MarzWorkbench#6]
By Accident I noticed that the midline length on the body dcrawing affects were the neck is placed on the body. What is this relationship?

**Comment by mnesarco** [comment]
The intersection of the middle line with the body contour determines the position where the neck will be placed. Intersection of midline with contour matches "Joint Fret"

**Comment by mnesarco** [comment]
Also the midline MUST intercept contour in ONLY ONE PLACE.
