### ISSUE TITLE
how to do a carved top?

### ISSUE THREAD

**Issue by s0ggyt4c0** [mnesarco/MarzWorkbench#9]
hi, i'm pretty new to cad software and I was wondering how to do a carved top?

**Comment by mnesarco** [comment]
Hi, I am sorry, this channel is not for general questions about CAD software. There are some youtube videos about modeling guitars in CAD software. MarzWorkbench does not provide automatic carved tops yet, you have to do it by yourself using the CAD tools.

**Comment by s0ggyt4c0** [comment]
ok thanks :)
